log_file="./log.xml"

[client]
server="example.com"
port=1081
username="username"
password="password"
doh="cloudflare"    #cloudflare, quad9

[server]
port=80
pretend="www.kernel.org"
doh="null"    #null, cloudflare, quad9

[db]
type="sqlite3" #sqlite3, mysql, postgresql, sqlserver
username="root"
password="password"
host="localhost"
port=1433
database="relaybaton.db"