log_file="./log.xml"

[client]
server="example.com"
port=1081
username="username"
password="password"

[server]
port=80
pretend="www.kernel.org"

[dns]
type="dot"
server="cloudflare-dns.com"
addr="1.0.0.1:853"
local_resolve=true

[db]
type="sqlite3" #sqlite3, mysql, postgresql, sqlserver
username="root"
password="password"
host="localhost"
port=1433
database="relaybaton.db"