name: CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      - name: Build
        run: bash .github/android-build.sh
      - uses: actions/upload-artifact@master
        with:
          name: relaybaton
          path: "bin"
      - uses: actions/upload-artifact@master
        with:
          name: relaybaton-aar
          path: "relaybaton.aar"